python_loc/test_field2: ignore zeroes from DWM module
These zeroes cause exception inside least_squares.py:

Traceback (most recent call last):
  File "python_loc/test_field2.py", line 429, in <module>
    X_calc = calc_pos(X0, loc)
  File "python_loc/test_field2.py", line 382, in calc_pos
    res = least_squares(func1, X0, loss='cauchy', f_scale=0.001, bounds=(lowb, upb),
  File "/home/roman/.local/lib/python3.8/site-packages/scipy/optimize/_lsq/least_squares.py", line 925, in least_squares
    result = trf(fun_wrapped, jac_wrapped, x0, f0, J0, lb, ub, ftol, xtol,
  File "/home/roman/.local/lib/python3.8/site-packages/scipy/optimize/_lsq/trf.py", line 123, in trf
    return trf_bounds(
  File "/home/roman/.local/lib/python3.8/site-packages/scipy/optimize/_lsq/trf.py", line 220, in trf_bounds
    J, f = scale_for_robust_loss_function(J, f, rho)
  File "/home/roman/.local/lib/python3.8/site-packages/scipy/optimize/_lsq/common.py", line 732, in scale_for_robust_loss_function
    f *= rho[1] / J_scale
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'